#.streamlit/config.toml

[server]
port = 8502

[client]
showErrorDetails = false

[theme]

# Primary accent for interactive elements
primaryColor = '#ffe090'

# Background color for the main content area
backgroundColor = '#273346'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#683aff'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"